name: docker-exporter
port: 9550
endpoint: /metrics
metrics:
- name: docker_container_states_containers
  help: The count of containers in various states
  type: gauge
  executions:
  - type: sh
    command: docker info --format '{{ .ContainersRunning }}'
    timeout: 500
    labels:
      state: Running
  - type: sh
    command: docker info --format '{{ .ContainersStopped }}'
    timeout: 500
    labels:
      state: Stopped
  - type: sh
    command: docker info --format '{{ .ContainersPaused }}'
    timeout: 500
    labels:
      state: Paused
- name: docker_image_types_images
  help: The count of images of various types
  type: gauge
  executions:
  - type: sh
    command: docker images --quiet --filter dangling=true | wc -l
    timeout: 500
    labels:
      type: dangling
  - type: sh
    command: docker images --quiet | wc -l
    timeout: 500
    labels:
      type: top-level
  - type: sh
    command: expr `docker images --all --quiet | wc -l` - `docker images --quiet | wc -l`
    timeout: 500
    labels:
      type: intermediate